services:
  postgres:
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=api
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest
    ports:
      - 6379:6379

volumes:
  postgres:
